### ISSUE TITLE
Fresh demos parse error

### ISSUE THREAD

**Issue by CodeAndRun** [saul/demofile#108]
Example demo (fail on both .dem files): https://www.hltv.org/download/demo/47064
Same error almost on all fresh demos.

Stack trace:
```
Fail x6tence-galaxy-vs-windigo-m1-overpass.dem { error:
   Error: Cannot get 32 bit(s) from offset 26040, 16 available
       at BitView.getBits (../demofile/node_modules/bit-buffer/bit-buffer.js:58:9)
       at BitView.bit_buffer_1.BitView.getBits (../demofile/dist/ext/bitbuffer.js:33:28)
       at BitStream.readBits (../demofile/node_modules/bit-buffer/bit-buffer.js:273:23)
       at BitStream.bit_buffer_1.BitStream.readUBits (../demofile/dist/ext/bitbuffer.js:51:17)
       at Object.bitbuf [as decode] (../demofile/dist/props.js:81:41)
       at Entities._parseEntityUpdate (../demofile/dist/entities.js:338:38)
       at Entities._parseInstanceBaseline (../demofile/dist/entities.js:436:31)
       at Entities.handleDataTables (../demofile/dist/entities.js:205:56)
       at DemoFile._handleDataTables (../demofile/dist/demo.js:184:23)
       at DemoFile._parseRecurse (../demofile/dist/demo.js:223:26) }
```

Code to reproduce:
```
const fs = require("fs")
const DemoFile = require("demofile").DemoFile

let fnDemo = 'x6tence-galaxy-vs-windigo-m1-overpass.dem'
fs.readFile(fnDemo, (err, buffer) => {
  const demoFile = new DemoFile()

  demoFile.on("end", e => {
    if (e.error) console.log('Fail', fnDemo, e)
    else console.log('Success', fnDemo)
  })    

  demoFile.parse(buffer)
})
```

**Comment by saul** [comment]
This demo seems to parse fine for me - are you using v1.0.2 or higher?

**Comment by CodeAndRun** [comment]
Thanks - this was the issue
Update to 1.0.4 helped
