### ISSUE TITLE
Error: Cannot get 8 bit(s) from offset 9617, 7 available

### ISSUE THREAD

**Issue by onepass1** [saul/demofile#281]
Hello,
I can't parse any demo from hltv.org.

> "demofile": "^2.0.0-beta.4"

Code:

> const fs = require("fs");  
const demofile = require("demofile");
fs.readFile("nip-vs-havu-m1-mirage.dem", (err, buffer) => {
    const demoFile = new demofile.DemoFile();
  demoFile.parse(buffer);
});

Error message : 

> Error: Cannot get 8 bit(s) from offset 9617, 7 available  
    at BitView.getBits (\dev\node_modules\bit-buffer\bit-buffer.js:58:9)  
    at BitView.getUint8 (\dev\node_modules\bit-buffer\bit-buffer.js:122:14)  
    at BitStream.<anonymous> (\dev\node_modules\bit-buffer\bit-buffer.js:180:29)  
    at BitStream.bit_buffer_1.BitStream.readString (\dev\node_modules\demofile\dist\ext\bitbuffer.js:27:24)         
    at Object.bitbuf [as decode] (\dev\node_modules\demofile\dist\props.js:177:23)  
    at Entities._parseEntityUpdate (\dev\node_modules\demofile\dist\entities.js:400:38)  
    at Entities._parseInstanceBaseline (\dev\node_modules\demofile\dist\entities.js:558:31)  
    at Entities.handleDataTables (\dev\node_modules\demofile\dist\entities.js:238:54)  
    at DemoFile._handleDataTables (\dev\node_modules\demofile\dist\demo.js:196:23)  
    at DemoFile._parseRecurse (\dev\node_modules\demofile\dist\demo.js:355:26)

Can you help me ?
Thanks in advance

**Comment by saul** [comment]
Hi @onepass1 - please can you link to the affected demo?

**Comment by onepass1** [comment]
Hello @saul , 
It happens on all dem files from HLTV website.
Here is the link to download the .dem file of my posted example : https://www.hltv.org/download/demo/63285 (match: https://www.hltv.org/matches/2346889/nip-vs-havu-pinnacle-cup-2021 map:mirage).
OS: w10
Have a nice day!

**Comment by saul** [comment]
Strange - `nip-vs-havu-m1-mirage.dem` parses fine on my machine. Which version of node are you using? This library requires nodejs >= 12.0.0

**Comment by onepass1** [comment]
Sorry, I didn't notice the min required version!
I had v8; I switched to v14 and it worked nicely! 
Thank you for your help !
