### ISSUE TITLE
error TS2532: Object is possibly 'undefined'

### ISSUE THREAD

**Issue by dennyb** [saul/demofile#342]
### Research

- [X] I searched but did not find an existing issue or discussion about this bug.

### Description

Tried it with npm V17. and V16.
Downloaded the example demos but can't get the examples running.

```
/etc/demofile/examples # npx ts-node dumpfile.ts ../demos/pc419-vs-chiefs-mirage.dem

/etc/demofile/node_modules/ts-node/src/index.ts:500
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
dumpfile.ts:61:9 - error TS2532: Object is possibly 'undefined'.

61         terrorists.teamName,
           ~~~~~~~~~~
dumpfile.ts:62:9 - error TS2532: Object is possibly 'undefined'.

62         terrorists.clanName,
           ~~~~~~~~~~
dumpfile.ts:63:9 - error TS2532: Object is possibly 'undefined'.

63         terrorists.score,
           ~~~~~~~~~~
dumpfile.ts:64:9 - error TS2532: Object is possibly 'undefined'.

64         cts.teamName,
           ~~~
dumpfile.ts:65:9 - error TS2532: Object is possibly 'undefined'.

65         cts.clanName,
           ~~~
dumpfile.ts:66:9 - error TS2532: Object is possibly 'undefined'.

66         cts.score
           ~~~
dumpfile.ts:191:15 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

191 parseDemoFile(process.argv[2]);
                  ~~~~~~~~~~~~~~~

    at createTSError (/etc/demofile/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/etc/demofile/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/etc/demofile/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/etc/demofile/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/etc/demofile/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/etc/demofile/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

```

**Comment by saul** [comment]
Apologies for the delay - I've just fixed this.

The CI was only running one of the example scripts (scores.ts, which did work). I've changed this so that all example scripts are tested as part of each commit.
