### ISSUE TITLE
Demos not being parsed after last update

### ISSUE THREAD

**Issue by tugamars** [saul/demofile#40]
Ever since the update (i think it was this one: http://blog.counter-strike.net/index.php/2017/11/19757/), that demo parser are crashing very early in the game, on this: 

```
TypeError: Cannot read property 'slice' of undefined
    at _.reduce (/home/demos2/csgodemoparser/stringtables.js:193:38)
    at arrayReduce (/home/demos2/csgodemoparser/node_modules/lodash/index.js:1450:23)
    at Function.<anonymous> (/home/demos2/csgodemoparser/node_modules/lodash/index.js:3445:13)
    at StringTables._parseStringTableUpdate (/home/demos2/csgodemoparser/stringtables.js:175:7)
    at StringTables._handleUpdateStringTable (/home/demos2/csgodemoparser/stringtables.js:287:10)
    at emitOne (events.js:96:13)
    at DemoFile.emit (events.js:188:7)
    at DemoFile._handleDemoPacket (/home/demos2/csgodemoparser/demo.js:218:12)
    at DemoFile._parseRecurse (/home/demos2/csgodemoparser/demo.js:312:14)
    at runCallback (timers.js:672:20)
```

Solutions?

**Comment by tugamars** [comment]
I found out that at a certain moment the "history[index]" was finding and "Undefined" object and that was what caused the crash.

I fixed by doing a if, but not sure if it is the correct path.

**Comment by saul** [comment]
Can you upload a demo that exhibits the issue and I’ll investigate. Thanks

**Comment by tugamars** [comment]
This one per example: http://defs.pt/demo_download.php?id=2774

I thought it was happening with all form the new update but just realised that thats not the case. My bad.

**Comment by saul** [comment]
This is a problem with the demo file itself - even the official demoinfogo parser fails at the same point:

```
---- CNETMsg_Tick (12 bytes) -----------------
tick: 62648
host_computationtime: 4151
host_computationtime_std_deviation: 1661
host_framestarttime_std_deviation: 77
UpdateStringTable:3(soundprecache):14:
 2183, +player\vo\leet\t_flashbang03.wav, 31, ßÏ┬▄ÞÊ▄╬─Ì┌─`d\¯┬ý
 2184, Ó`═à═q╔àæÑ¢╣░¢ì¡╣▒¢àæ┼▄©▄à┘╔8Çradio_locknload06.wav, 0, (null)
 2185, +player\vo\leet\t_flashbang031.wav, 0, (null)
 2186, +player\vo\leet\t_fmolotov05.wav, 0, (null)
 2187, +player\vo\leet\t_fgrenade01.wav, 0, (null)
 2188, +player\vo\leet\t_fsmoke02.wav, 0, (null)
<debug assertion here>
```

The data does look a bit wrong - see index 2184 - there's a load of garbage data before radio_locknload06.wav. Maybe the demo download/upload got corrupted somewhere?
