### ISSUE TITLE
.on('error') handler for corrupt/incomplete demos

### ISSUE THREAD

**Issue by mavrick** [saul/demofile#53]
Hey mate,

I've been testing against a couple thousand demos and have noticed a good few of them are corrupt and it throws and exception. 

I'm running this as a lambda function so an exception is very expensive. It would be great to have an ``.on('error')`` handler.

Currently I've solved this with:
```javascript
process.on("uncaughtException", function (err) 
{
  console.error((new Date).toUTCString() + " uncaughtException:", err.message);
  console.error(err.stack);
});
```

Some of the errors I'm seeing:

```
at, 27 Jan 2018 02:24:38 GMT uncaughtException: Illegal offset: 0 <= 45087626 (+152) <= 45087696
RangeError: Illegal offset: 0 <= 45087626 (+152) <= 45087696
    at ByteBuffer.module.exports.ByteBufferPrototype.readBytes (C:\test\node_modules\bytebuffer\dist\bytebuffer-node.js:499:23)
    at DemoFile._handleDemoPacket (C:\test\node_modules\demofile\demo.js:197:44)
    at DemoFile._parseRecurse (C:\test\node_modules\demofile\demo.js:319:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: undefined
undefined
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: Illegal offset: 0 <= 45087693 (+4) <= 45087696
RangeError: Illegal offset: 0 <= 45087693 (+4) <= 45087696
    at ByteBuffer.module.exports.ByteBufferPrototype.readInt32 (C:\test\node_modules\bytebuffer\dist\bytebuffer-node.js:906:23)
    at DemoFile._parseRecurse (C:\test\node_modules\demofile\demo.js:306:32)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: Illegal offset: 0 <= 45087694 (+4) <= 45087696
RangeError: Illegal offset: 0 <= 45087694 (+4) <= 45087696
    at ByteBuffer.module.exports.ByteBufferPrototype.readInt32 (C:\test\node_modules\bytebuffer\dist\bytebuffer-node.js:906:23)
    at DemoFile._parseRecurse (C:\test\node_modules\demofile\demo.js:306:32)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: Illegal offset: 0 <= 45087695 (+4) <= 45087696
RangeError: Illegal offset: 0 <= 45087695 (+4) <= 45087696
    at ByteBuffer.module.exports.ByteBufferPrototype.readInt32 (C:\test\node_modules\bytebuffer\dist\bytebuffer-node.js:906:23)
    at DemoFile._parseRecurse (C:\test\node_modules\demofile\demo.js:306:32)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
Sat, 27 Jan 2018 02:24:38 GMT uncaughtException: Illegal offset: 0 <= 45087696 (+4) <= 45087696
RangeError: Illegal offset: 0 <= 45087696 (+4) <= 45087696
    at ByteBuffer.module.exports.ByteBufferPrototype.readInt32 (C:\test\node_modules\bytebuffer\dist\bytebuffer-node.js:906:23)
    at DemoFile._parseRecurse (C:\test\node_modules\demofile\demo.js:306:32)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

The demo's are indeed corrupt or the match was killed via a command or the server was killed/restarted. The ``.on('end')`` appears to be called for a few of the demos.

**Comment by saul** [comment]
Released in 0.4.12
