### ISSUE TITLE
TypeError on null/undefined player properties

### ISSUE THREAD

**Issue by ballerlina** [saul/demofile#78]
On some demos (ex: demo ID 41144, map 2 from HLTV), the resourceProp function seems to be passed an undefined object, which throws a TypeError. I've seen this happen for cashSpendThisRound and assists, which are also sometimes blank during a game without throwing an error. Is there a better way to handle these cases?

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Player.resourceProp (.../demo-parser/node_modules/demofile/entities/player.js:201:26)
    at Player.get cashSpendThisRound [as cashSpendThisRound] (.../demo-parser/node_modules/demofile/entities/player.js:229:17)
    at DemoFile.df.on.t (.../demo-parser/parser.js:115:83)
    at emitOne (events.js:121:20)
    at DemoFile.emit (events.js:211:7)
    at DemoFile._parseRecurse (.../demo-parser/node_modules/demofile/demo.js:313:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by saul** [comment]
Fixed in v0.4.20
