### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by derpalmer** [saul/demofile#9]
I got an error with [this demo file](http://replay195.valve.net/730/003190580341324644700_0563378655.dem.bz2)

```
C:\temp\git\demoanalyzer\node_modules\demofile\entities.js:54
    return this.props[tableName][varName];
                                ^

TypeError: Cannot read property 'm_iPrimaryAmmoType' of undefined
    at Entity.getProp (C:\temp\git\demoanalyzer\node_modules\demofile\entities.js:54:33)
    at Entities._readNewEntity (C:\temp\git\demoanalyzer\node_modules\demofile\entities.js:414:29)
    at Entities._handlePacketEntities (C:\temp\git\demoanalyzer\node_modules\demofile\entities.js:451:14)
    at emitOne (events.js:77:13)
    at DemoFile.emit (events.js:169:7)
    at DemoFile._handleDemoPacket (C:\temp\git\demoanalyzer\node_modules\demofile\demo.js:177:12)
    at DemoFile._parseRecurse (C:\temp\git\demoanalyzer\node_modules\demofile\demo.js:271:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Is the demo file broken or is there something with the library? Thanks!

**Comment by saul** [comment]
Just published demofile 0.3.1 that fixes this problem - thanks for reporting.
