### ISSUE TITLE
parseHeader fails

### ISSUE THREAD

**Issue by CodeAndRun** [saul/demofile#93]
Trying to parse demo from this match: https://www.hltv.org/matches/2328729/ldlc-vs-optic-ecs-season-6-europe

```
TypeError: Illegal buffer
    at Function.module.exports.ByteBuffer.wrap (./demofile/node_modules/bytebuffer/dist/bytebuffer-node.js:346:19)
    at parseHeader (./demofile/dist/demo.js:29:32)
    at DemoFile.parse (./demofile/dist/demo.js:130:23)
    at ReadFileContext.fs.readFile [as callback] (./index.js:133:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

At the same demo official Valve demoinfo parser passes OK

**Comment by CodeAndRun** [comment]
Sorry, my bad.. targeted wrong file
