### ISSUE TITLE
Bit issues received from offsets

### ISSUE THREAD

**Issue by Technoblazed** [saul/demofile#95]
I've started receiving these errors after the recent cs:go updates, I've tried to look into patching it myself but I'm lost in your codebase :P 

```
Error: Cannot get 32 bit(s) from offset 26225, 15 available
    at BitView.getBits (/home/techno/projects/demo-processor/node_modules/bit-buffer/bit-buffer.js:58:9)
    at BitView.bitBuffer.BitView.getBits (/home/techno/projects/demo-processor/node_modules/demofile/ext/bitbuffer.js:38:26)
    at BitStream.readBits (/home/techno/projects/demo-processor/node_modules/bit-buffer/bit-buffer.js:273:23)
    at BitStream.bitBuffer.BitStream.readUBits (/home/techno/projects/demo-processor/node_modules/demofile/ext/bitbuffer.js:54:15)
    at PropDecoder.intDecode (/home/techno/projects/demo-processor/node_modules/demofile/props.js:87:30)
    at PropDecoder.decode (/home/techno/projects/demo-processor/node_modules/demofile/props.js:53:21)
    at Entities._parseEntityUpdate (/home/techno/projects/demo-processor/node_modules/demofile/entities.js:466:63)
    at Entities._parseInstanceBaseline (/home/techno/projects/demo-processor/node_modules/demofile/entities.js:529:25)
    at Entities._handleDataTables (/home/techno/projects/demo-processor/node_modules/demofile/entities.js:356:48)
    at DemoFile._handleDataTables (/home/techno/projects/demo-processor/node_modules/demofile/demo.js:232:19)
    at DemoFile._parseRecurse (/home/techno/projects/demo-processor/node_modules/demofile/demo.js:324:16)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by saul** [comment]
Hi @Technoblazed 

Can you send me an example of a demo which is hitting this problem?

Thanks
Saul

**Comment by OrelStealth** [comment]
Hi, I have got the same problem with most of demos.

Here is an example of demos which I cannot parse:
http://replay144.valve.net/730/003315582061644873864_1176508759.dem.bz2
http://replay181.valve.net/730/003316342541439206122_1241784625.dem.bz2

And example of demo after the latest update which is surprisingly working well:
http://replay181.valve.net/730/003315967837754884195_1963389272.dem.bz2

**Comment by BitDesert** [comment]
I have the issue too, some sharecodes:
CSGO-FxTAk-4phAF-5jfSU-TVOBm-MPN2G
CSGO-uVV4f-xVGFT-oDTy7-tO76v-sNjeC
CSGO-XZGFn-NOhMN-M4ViX-93yFR-vmdBN

**Comment by Technoblazed** [comment]
Its any demo created after the DZ update, I’ll get one to you later.

**Comment by OrelStealth** [comment]
> Its any demo created after the DZ update, I’ll get one to you later.

not any, but most of them

**Comment by saul** [comment]
Thanks all I’ll take a look at this tomorrow. Should be an easy fix

**Comment by Technoblazed** [comment]
Looks like https://github.com/saul/demofile/pull/97 stopped it completely crashing out, probably moreso to look into why it's giving funky offsets now

**Comment by alexhelkar** [comment]
#97 changed the way an Error is triggered. Previously it was an uncatchable exception, not it is a warning.

if you do something like this, you would see exactly the same error you have mentioned in the first message.
```
process.on('warning', (warning) => {
  console.warn(warning.name);    // 'Warning'
  console.warn(warning.message); // 'Something happened!'
  console.warn(warning.code);    // 'MY_WARNING'
  console.warn(warning.stack);   // Stack trace
  console.warn(warning.detail);  // 'This is some additional information'
});
```

**Comment by thorebear** [comment]
I get this error from every demo I have tried to parse after the new update so far.

**Comment by alexhelkar** [comment]
Same thing here. All new demos lead to this error. 
@saul do you have any clues on where the issue is or the way it could be fixed? 

I could try to work on a fix.

**Comment by alexhelkar** [comment]
Guys, does anyone know any workaround for this issue? 
@saul sorry, for bothering you. Do you have any news or updates?

**Comment by saul** [comment]
Sorry guys - no update as of yet. I will dig into it this weekend. I hope you can appreciate it’s a busy time of year 😄

**Comment by billfreeman44** [comment]
any update @saul ? <3 xoxo

**Comment by saul** [comment]
Sorry all - I will be looking at this in the new year. I’ve reached out to some Valve developers but no leads yet. 

I think disabling instance baseline parsing may work around the issue for now. I’ll do an emergency release of that first (in the next week or so) before digging into this again.

**Comment by MRuy** [comment]
StatsHelix/demoinfo updated his C#-Library
Maybe that helps
https://github.com/StatsHelix/demoinfo/commit/2412dac4c2f6ecc962ef60b8585d2b58273facee

**Comment by saul** [comment]
Thanks for the link, but we’ve had int64 support since day 1. There’s some other incompatibility I think.


________________________________

**Comment by vklymniuk** [comment]
https://github.com/SteamRE/SteamKit/commit/4c4a538d37773fdaaa4b02b2a4c67887790cb61d ?

**Comment by jnettome** [comment]
@vklymniuk @saul that's the point! I'll try those changes as seen in SteamKit and StatsHelix on our fork and keep u guys updated

**Comment by kpei** [comment]
hey everyone, im posting this as im having similar issues on the python end for demoparsing ever since dz update. adding int64 support didnt fix it. The demo is having trouble finding certain entities on the pytho  end. I suspect its the same issue as you guys are having.  The statshelix demoinfo seem to be parsing fine so im trying to realign my code to follow their methods.


Does the latest commit allow the demos to be still parsed with everything accurate? Or is the issue still persistent?

**Comment by Technoblazed** [comment]
@kpei It's still an ongoing issue.

**Comment by kpei** [comment]
> @kpei Do you try to use latest protobufs structures? https://github.com/SteamDatabase/Protobufs/tree/master/csgo

Yes I updated to latest protobufs, still the same issue.  DemoInfo was able to parse fine w.o updating to new protobufs so I felt that's not the issue.

**Comment by JeffreyLimbacher** [comment]
I found an issue on https://github.com/saul/demofile/blob/ceab224d3275547e8c9606e8fd7d9a52630fd27d/src/props.ts#L255

The line `const numBits = Math.ceil(Math.log2(maxElements)) + 1;` should be `const numBits = Math.ceil(Math.log2(maxElements));`. 

However, fixing that line gives me a new issue:

```Error: delta on deleted entity
index.js:9
    at Object.assertExists [as default] (d:\Git Repos\csgo\try_node_demo_parser\node_modules\ts-assert-exists\lib\index.js:9:15)
    at Entities._handlePacketEntities (d:\Git Repos\csgo\try_node_demo_parser\node_modules\demofile\dist\entities.js:441:58)
    at DemoFile.demo.on.e (d:\Git Repos\csgo\try_node_demo_parser\node_modules\demofile\dist\entities.js:99:49)
    at DemoFile.emit (events.js:182:13)
    at DemoFile._handleDemoPacket (d:\Git Repos\csgo\try_node_demo_parser\node_modules\demofile\dist\demo.js:166:22)
    at DemoFile._parseRecurse (d:\Git Repos\csgo\try_node_demo_parser\node_modules\demofile\dist\demo.js:214:26)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
(I wouldn't trust the line number from the stack as I've been changing a bunch of files to trace the issue down.)

I was testing using the first demo referenced by https://github.com/saul/demofile/issues/95#issuecomment-445478901.
